export const INITIALISED = 'INITIALISED';
export const SET_LOCATION_ID = 'SET_LOCATION_ID';
export const SET_MY_LOCATION = 'SET_MY_LOCATION';
export const SET_CONTACTS = 'SET_CONTACTS';
export const TOGGLE_CONTACTS_PANEL = 'TOGGLE_CONTACTS_PANEL';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const RESET = 'RESET';